version: "3.9"

services:
  api:
    build: ./Backend
    volumes:
      - ./Backend:/code
    ports:
      - "8000:8000"
  vue:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"